use_frameworks!

target 'testpod_Example' do
  pod 'testpod', :path => '../'

  target 'testpod_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
